# This workflow will install Python dependencies and run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage nbformat nbconvert unittest-xml-reporting
        pip install -e .[dev]
#    - name: Test notebooks
#      run: |
#        cd tutorials; python -m unittest discover
    - name: Test source
      run: |
        cd tests; coverage run -m unittest discover
        ls -a . # DEBUG check root
        ls -a tests # DEBUG check tests
        # mv tests/.coverage . # Move coverage file for upload to Codecov
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
